prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- ORACLE Application Express (APEX) export file
--
-- You should run the script connected to SQL*Plus as the Oracle user
-- APEX_190100 or as the owner (parsing schema) of the application.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_api.import_begin (
 p_version_yyyy_mm_dd=>'2019.03.31'
,p_release=>'19.1.0.00.15'
,p_default_workspace_id=>1304835857079617
,p_default_application_id=>108465
,p_default_owner=>'STRACK_DEV'
);
end;
/
prompt --application/shared_components/plugins/process_type/com_strack_software_filter_uploaded_data
begin
wwv_flow_api.create_plugin(
 p_id=>wwv_flow_api.id(81643413197994929)
,p_plugin_type=>'PROCESS TYPE'
,p_name=>'COM.STRACK-SOFTWARE.FILTER_UPLOADED_DATA'
,p_display_name=>'Filter Uploaded Data'
,p_supported_ui_types=>'DESKTOP:JQM_SMARTPHONE'
,p_api_version=>1
,p_execution_function=>'import_filter_plugin.Filter_Upload'
,p_substitute_attributes=>true
,p_subscribe_plugin_settings=>true
,p_help_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Plugin for filtering uploaded data.',
'',
'If you get an "ORA-06502: PL/SQL: numeric or value error: character string buffer too small" error',
'when you try to process the uploaded data or only a small subset of the uploaded rows is processed',
'then use this plugin to filter the uploaded data.',
'',
'If you encounter errors in the attempt to process an uploaded file or pasted data,',
'and you have a large import file it can be difficult to find the bad rows that cause the error.',
'In this case you can use this plugin to extract the bad formated rows with a row number into a page item.',
'',
'When a row has fewer columns than the count of columns found in the first row it is a bad row.',
'The filter process removes bad rows from the input and returns the bad rows with a row number in the bad rows item.',
'The bad rows can be optionally displayed on the "Data Validation" or "Upload Results" page.',
'You have to create a Page Item PXX_BAD_ROWS . The PXX_BAD_ROWS has to be set in the ''Bad Rows Item'' attribute of the plugin.',
'',
'To use this plugin navigate to a "XX - Data Load Source" page in your application.',
'Create a Page process.',
'Choose ''Process type'' "Plug-ins".',
'Select Plug-in "Filter Uploaded Data".',
'Set ''Name'' to "Filter Uploaded Data".',
'Set ''Sequence'' to 5 to ensure that the process is executed before the "Parse Uploaded Data" process.',
'Set ''Point'' to "On Submit - After Computations and Validations"',
'At ''Process Condition'' set ''When Button Pressed'' to "NEXT".',
'',
'Now edit the settings of the plugin instance.',
'Set the mandantory attributes ''Import From Item'', ''Separator Item'', ''File Name Item'' and ''Character Set Item''',
'to the same values that are used in the "Parse Uploaded Data" process.',
'',
'Set the optional attribute ''Bad Rows Limit''. Define the maximum number of rows to be returned into the bad rows Item.',
'',
'Set the optional attribute ''Show Success Message''. Set this attribute to ''Yes'' when a success message should be displayed.',
'The Message is of the form "Filtered uploaded data. Found %0 good rows and %1 bad rows." and is displayed,',
'when a page branch with the option ''include process success message '' is followed.',
'',
'Set the optional attribute ''Bad Rows Item'' Enter the page item to receive the bad rows.',
'You can type in the name or pick from the list of available items.',
'When the Plugin is processed, rows that do not contain the proper formating will be removed',
'from the input data and will by added to the bad rows item.',
'',
'In order to display the bad rows that where filtered from the input data,',
'navigate to the page "XX - Data / Table Mapping" or "XX - Data Load Results" that was generated by the Data Load wizard.',
'Create a region of type ''Static Content'' named "Bad Input Rows".',
'Set Sequence to 5 to ensure that the Region is shown on top of the page.',
'Set Condition Type to ''Item IS NOT NULL'' and ''Expression 1'' to PXX_BAD_ROWS.',
'Create a page item PXX_BAD_ROWS of type ''Display Only'' in the Region "Bad Input Rows".',
'Set "Template" to ''Hidden'' and "Label Column Span" to 0, so that all available screen space can bee used.',
'Navigate back to the "XX - Data Load Source" and assign the PXX_BAD_ROWS item name to "Bad Rows Item".',
'',
'The process is skipped when not data can be processced and one of the following success messages is returned:',
'''File name is empty.'', ''Line delimiter not found.'', ''Separator not found in first line.''.',
'the messages can be translated via enties in the Dynamic Translations Lists'))
,p_version_identifier=>'1.0'
,p_plugin_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'The package IMPORT_FILTER_PLUGIN has to be installed in the application schema. ',
'execute the file filter_uploaded_data_plsql_code.sql to install the required database objects.',
'You can add the file to the installation script of you application.',
''))
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(81660924314410116)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>1
,p_display_sequence=>10
,p_prompt=>'Import From Item'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>true
,p_is_translatable=>false
,p_examples=>'PXX_IMPORT_FROM'
,p_help_text=>'Enter the page item to hold the Import From option chosen by the end user. You can type in the name or pick from the list of available items.'
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(81670885821688760)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>2
,p_display_sequence=>20
,p_prompt=>'Separator Item'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>true
,p_is_translatable=>false
,p_examples=>'PXX_SEPARATOR'
,p_help_text=>'Enter the page item to hold the Seperator text entered by the end user. You can type in the name or pick from the list of available items.'
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(81671255487693694)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>3
,p_display_sequence=>30
,p_prompt=>'File Name Item'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>true
,p_is_translatable=>false
,p_examples=>'PXX_FILE_NAME'
,p_help_text=>'Enter the page item to hold the File Name value entered by the end user. You can type in the name or pick from the list of available items.'
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(81671499851701108)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>4
,p_display_sequence=>40
,p_prompt=>'Character Set Item'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>false
,p_is_translatable=>false
,p_examples=>'PXX_CHAR_SET'
,p_help_text=>'Enter the page item to hold the File Character Set selected by the end user. You can type in the name or pick from the list of available items.'
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(81671831496733906)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>5
,p_display_sequence=>50
,p_prompt=>'Bad Rows Item'
,p_attribute_type=>'PAGE ITEM'
,p_is_required=>false
,p_is_translatable=>false
,p_examples=>'PXX_BAD_ROWS'
,p_help_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Enter the page item to receive the bad rows. ',
'You can type in the name or pick from the list of available items.',
'When the Plugin is processed, rows that do not contain the proper formating will be removed ',
'from the input data and will by added to the bad rows item.',
'',
'In order to display the bad rows that where filtered from the input data,',
'navigate to the page "XX - Data Validation" or "XX - Data Load Results" that was generated by the Data Load wizard. ',
'Create a region of type ''Static Content'' named "Bad Input Rows". ',
'For Conditional Display set Condition type to ''item /column not null'' and ''Expression 1'' to PXX_BAD_ROWS.',
'Create a page item PXX_BAD_ROWS of type ''Display Only'' in the Region "Bad Input Rows". ',
'Set "Template" to ''Hidden'' and "Label Column Span" to 0',
'Navigate back to the "XX  - Data Load Source" and assign the PXX_BAD_ROWS item name to "Bad Rows Item".'))
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(81791338686937645)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>6
,p_display_sequence=>60
,p_prompt=>'Bad Rows Limit'
,p_attribute_type=>'NUMBER'
,p_is_required=>false
,p_default_value=>'200'
,p_display_length=>10
,p_max_length=>10
,p_unit=>'rows'
,p_is_translatable=>false
,p_help_text=>'Define the maximum number of rows to be returned into the bad rows Item.'
);
wwv_flow_api.create_plugin_attribute(
 p_id=>wwv_flow_api.id(82090960988643886)
,p_plugin_id=>wwv_flow_api.id(81643413197994929)
,p_attribute_scope=>'COMPONENT'
,p_attribute_sequence=>7
,p_display_sequence=>70
,p_prompt=>'Show Success Message'
,p_attribute_type=>'CHECKBOX'
,p_is_required=>false
,p_default_value=>'Y'
,p_is_translatable=>false
,p_help_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Set this attribute to ''Yes'' when a Success Message should be displayed.',
'The Message is of the form "Filtered uploaded data. Found %0 good rows and %1 bad rows." and is displayed, when a page branch with the option ''include process success message '' is followed.'))
);
end;
/
begin
wwv_flow_api.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false), p_is_component_import => true);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
